###
GET http://localhost:3000/api/favorite-heroes

###
POST http://localhost:3000/api/favorite-heroes
Content-Type: application/json
{
  "heroId": "1009157"
}

###
GET http://localhost:3000/api/heroes
Content-Type: application/json
{
  "query": "spider"
}