name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs_on: ubunto-latest

    steps:
      - name: Verify code
        uses: actions/checkout@v2

      - name: Config Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
